### ISSUE TITLE
mongo로 쿼리 넣어서 temp collection 만드는 데 까지의 성능 향상

### ISSUE THREAD

**Issue by orslow2** [orslow/matmul-performance-eval#1]
hadoop에서 mongo로 query를 넣어서 temp collection을 만드는 데까지만 1분 30~31초 소요되는데(spark에서 blockmatrix로 matrix multiply 마치는 시간은 50초 미만), spark에서 temp collection을 만드는 데까지 hadoop과 다른 성능적 이득을 얻을 수 있는 부분이 있는지.

**Comment by orslow2** [comment]
mongodb 자체의 config를 만져서 성능 향상을 꾀해보기?

**Comment by hyu-leeky** [comment]
음. 어쩌면 샤딩없이 temp 를 만들경우 물리적 한계일수도...
어쨋거나 이게 목표가 스파크보다 빨리 하는건 아니니, 스파크의 숫자에 너무 연연하지는 말자.
